export const MAIN = {
  HEROES_FETCHING: 'HEROES_FETCHING',
  HEROES_FETCHED: 'HEROES_FETCHED',
  HEROES_FETCHING_ERROR: 'HEROES_FETCHING_ERROR',
  HEROES_DELETE: 'HEROES_DELETE',
  HEROES_ADD_FORM: 'HEROES_ADD_FORM',
  ELEMENTS_FETCHING: 'ELEMENTS_FETCHING',
  ELEMENTS_FETCHED: 'ELEMENTS_FETCHED',
  ELEMENTS_FETCHING_ERROR: 'ELEMENTS_FETCHING_ERROR',
  HEROES_FILTER: 'HEROES_FILTER',
};

export const STATUS = {
  LOADING: 'LOADING',
  IDLE: 'IDLE',
  ERROR: 'ERROR',
};
